spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jbp
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
    properties:
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
multitenancy:
 tenants:
   master:
     url: jdbc:mysql://localhost:3306/jbp
     username: root
     password: root
     driver-class-name: com.mysql.cj.jdbc.Driver
   yufu:
     url: jdbc:mysql://localhost:3306/jbp
     username: root
     password: root
     driver-class-name: com.mysql.cj.jdbc.Driver
