<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.github.yufucn</groupId>
    <artifactId>jbp-dependencies</artifactId>
    <version>1.0.5</version>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <spring-boot.version>2.7.13</spring-boot.version>
        <spring-cloud-alibaba.version>2021.0.5.0</spring-cloud-alibaba.version>
        <spring-cloud.version>2021.0.8</spring-cloud.version>
        <io.springfox.version>2.9.2</io.springfox.version>
        <org.mapstruct.version>1.4.2.Final</org.mapstruct.version>
        <querydsl.version>5.0.0.M1</querydsl.version>
        <org.projectlombok.version>1.18.18</org.projectlombok.version>
        <hutool.version>5.5.8</hutool.version>
        <hutool.version>5.5.8</hutool.version>
        <druid.version>1.2.19</druid.version>
        <fastjson.version>1.2.83</fastjson.version>
        <knife4j-spring-boot-starter.version>2.0.9</knife4j-spring-boot-starter.version>
        <knife4j-spring-ui.version>2.0.9</knife4j-spring-ui.version>
        <mysql-connector-java.version>8.0.30</mysql-connector-java.version>
        <hutool.version>5.8.25</hutool.version>
        <hibernate-validator.version>6.2.5.Final</hibernate-validator.version>
        <jbp.version>1.0.5</jbp.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- SpringCloud 微服务 -->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter</artifactId>
                <version>${spring-boot.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-all</artifactId>
                <version>5.5.8</version>
            </dependency>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-webmvc</artifactId>
                <version>5.3.28</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-jdbc</artifactId>
                <version>5.3.28</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>com.querydsl</groupId>
                <artifactId>querydsl-apt</artifactId>
                <version>${querydsl.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-orm</artifactId>
                <version>5.3.28</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-web</artifactId>
                <version>5.3.28</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-autoconfigure</artifactId>
                <version>2.7.13</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>com.querydsl</groupId>
                <artifactId>querydsl-jpa</artifactId>
                <version>${querydsl.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.data</groupId>
                <artifactId>spring-data-jpa</artifactId>
                <version>2.7.13</version>
            </dependency>
            <dependency>
                <groupId>javax.persistence</groupId>
                <artifactId>javax.persistence-api</artifactId>
                <version>2.2</version>
            </dependency>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-context</artifactId>
                <version>5.3.28</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.data</groupId>
                <artifactId>spring-data-commons</artifactId>
                <version>2.7.13</version>
            </dependency>

            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-web</artifactId>
                <version>2.7.13</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-data-jpa</artifactId>
                <version>2.7.13</version>
            </dependency>
            <dependency>
                <groupId>jakarta.persistence</groupId>
                <artifactId>jakarta.persistence-api</artifactId>
                <version>2.2.3</version>
            </dependency>
            <dependency>
                <groupId>io.springfox</groupId>
                <artifactId>springfox-swagger2</artifactId>
                <version>${io.springfox.version}</version>
            </dependency>
            <dependency>
                <groupId>io.springfox</groupId>
                <artifactId>springfox-swagger-ui</artifactId>
                <version>${io.springfox.version}</version>
            </dependency>
            <dependency>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-annotations</artifactId>
                <version>1.6.2</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>fastjson</artifactId>
                <version>${fastjson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.xiaoymin</groupId>
                <artifactId>knife4j-spring-boot-starter</artifactId>
                <version>${knife4j-spring-boot-starter.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.security</groupId>
                <artifactId>spring-security-config</artifactId>
                <version>5.5.2</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.security</groupId>
                <artifactId>spring-security-core</artifactId>
                <version>5.5.2</version>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${org.projectlombok.version}</version>
            </dependency>
            <dependency>
                <groupId>org.hibernate.validator</groupId>
                <artifactId>hibernate-validator</artifactId>
                <version>${hibernate-validator.version}</version>
            </dependency>
<!--            <dependency>-->
<!--                <groupId>org.hibernate</groupId>-->
<!--                <artifactId>hibernate-core</artifactId>-->
<!--                <version>6.4.6.Final</version>-->
<!--            </dependency>-->
<!--            <dependency>-->
<!--                <groupId>org.hibernate.orm</groupId>-->
<!--                <artifactId>hibernate-core</artifactId>-->
<!--                <version>6.4.0.Final</version>-->
<!--            </dependency>-->
            <dependency>
                <groupId>mysql</groupId>
                <artifactId>mysql-connector-java</artifactId>
                <version>${mysql-connector-java.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${org.mapstruct.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.yufucn</groupId>
                <artifactId>jbp-auditing</artifactId>
                <version>${jbp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.yufucn</groupId>
                <artifactId>jbp-caching</artifactId>
                <version>${jbp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.yufucn</groupId>
                <artifactId>jbp-core</artifactId>
                <version>${jbp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.yufucn</groupId>
                <artifactId>jbp-data</artifactId>
                <version>${jbp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.yufucn</groupId>
                <artifactId>jbp-ddd-application-contracts</artifactId>
                <version>${jbp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.yufucn</groupId>
                <artifactId>jbp-ddd-application</artifactId>
                <version>${jbp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.yufucn</groupId>
                <artifactId>jbp-ddd-domain-shared</artifactId>
                <version>${jbp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.yufucn</groupId>
                <artifactId>jbp-ddd-domain</artifactId>
                <version>${jbp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.yufucn</groupId>
                <artifactId>jbp-eventbus</artifactId>
                <version>${jbp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.yufucn</groupId>
                <artifactId>jbp-exception</artifactId>
                <version>${jbp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.yufucn</groupId>
                <artifactId>jbp-guids</artifactId>
                <version>${jbp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.yufucn</groupId>
                <artifactId>jbp-mapping</artifactId>
                <version>${jbp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.yufucn</groupId>
                <artifactId>jbp-multitenancy-abstractions</artifactId>
                <version>${jbp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.yufucn</groupId>
                <artifactId>jbp-multitenancy</artifactId>
                <version>${jbp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.yufucn</groupId>
                <artifactId>jbp-security</artifactId>
                <version>${jbp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.yufucn</groupId>
                <artifactId>jbp-specifications</artifactId>
                <version>${jbp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.yufucn</groupId>
                <artifactId>jbp-springframework</artifactId>
                <version>${jbp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.yufucn</groupId>
                <artifactId>jbp-springframework-mvc</artifactId>
                <version>${jbp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.yufucn</groupId>
                <artifactId>jbp-springframework-mvc-contracts</artifactId>
                <version>${jbp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.yufucn</groupId>
                <artifactId>jbp-timing</artifactId>
                <version>${jbp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.yufucn</groupId>
                <artifactId>jbp-tests</artifactId>
                <version>${jbp.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>